// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy9X9y9RNmz7a6XZ8uMDUk1kjbcu1wmnk',
    appId: '1:501446163023:web:43eb17c51026ceb99e083a',
    messagingSenderId: '501446163023',
    projectId: 'coursework6-5dfe1',
    authDomain: 'coursework6-5dfe1.firebaseapp.com',
    storageBucket: 'coursework6-5dfe1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm80J4-Vq9NhbeAoUz32jd_z46REQpWCw',
    appId: '1:501446163023:android:165bc34567b36d719e083a',
    messagingSenderId: '501446163023',
    projectId: 'coursework6-5dfe1',
    storageBucket: 'coursework6-5dfe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksrTJL_H81t-XjhjImsLr6iQS9_zezqk',
    appId: '1:501446163023:ios:7db63849024f34be9e083a',
    messagingSenderId: '501446163023',
    projectId: 'coursework6-5dfe1',
    storageBucket: 'coursework6-5dfe1.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAksrTJL_H81t-XjhjImsLr6iQS9_zezqk',
    appId: '1:501446163023:ios:7db63849024f34be9e083a',
    messagingSenderId: '501446163023',
    projectId: 'coursework6-5dfe1',
    storageBucket: 'coursework6-5dfe1.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy9X9y9RNmz7a6XZ8uMDUk1kjbcu1wmnk',
    appId: '1:501446163023:web:2261fee031c814299e083a',
    messagingSenderId: '501446163023',
    projectId: 'coursework6-5dfe1',
    authDomain: 'coursework6-5dfe1.firebaseapp.com',
    storageBucket: 'coursework6-5dfe1.firebasestorage.app',
  );
}
